#!/usr/bin/env python

import sys
import os

import cbopensource.connectors.skyatp.bridge as bridge
from cbopensource.connectors.skyatp.version import __version__

if __name__ == "__main__":
    name = "carbonblack-skyatp-connector"

    # set the path to the CA certificate PEM file to our local cache
    cacert_pem_path = "/usr/share/cb/integrations/skyatp/cacert.pem"
    if os.path.isfile(cacert_pem_path):
        os.environ["REQUESTS_CA_BUNDLE"] = cacert_pem_path

    daemon = bridge.SkyAtpBridge(name,configfile="/etc/cb/integrations/skyatp/carbonblack-skyatp-connector.conf")
    arglen = len(sys.argv)
    if arglen >= 2:
        if 'start' == sys.argv[1]:
            daemon.start()
        elif 'stop' == sys.argv[1]:
            daemon.stop()
        elif 'restart' == sys.argv[1]:
            daemon.restart()
            elif 'version' == sys.argv[1]:
            print "%s - version %s" % (name, __version__)
        elif 'show_blacklist' == sys.argv[1]:
            print daemon.get_blacklist()
        elif 'show_whitelist' == sys.argv[1]:
            print daemon.get_whitelist()
        elif 'clear_whitelist' == sys.argv[1]:
            daemon.clear_whitelist() if arglen == 2 else daemon.clear_whitelist(ips_to_remove=sys.argv[1:])
        elif 'clear_blacklist' == sys.argv[1]:
            #default to clearing blacklist else remove just the selected IPS
            daemon.clear_blacklist() if arglen == 2 else daemon.clear_blacklist(ips_to_remove=sys.argv[1:])
        else:
            print "Unknown command: %s" % sys.argv[1]
            sys.exit(2)

    else:
        print "Usage: %s start|stop|restart|version|show_blacklist|show_whitelist|clear_whitelist|clear_blacklist" % sys.argv[0]
        sys.exit(2)

    sys.exit(0)
