#!/usr/bin/env python

import os
import sys

sys.path.insert(0, "../../lib/cbapi/client_apis/python/src/cbapi/")
sys.path.insert(0, "../../lib/src/")

import cbfidelisbridge.bridge
import cbfidelisbridge.version

if __name__ == "__main__":
    name = "carbonblack_fidelis_bridge"
    daemon = cbfidelisbridge.bridge.CarbonBlackFidelisBridge(name, os.path.abspath("root/etc/cb/integrations/carbonblack_fidelis_bridge/carbonblack_fidelis_bridge.conf"))
    if len(sys.argv) == 2:
        if 'start' == sys.argv[1]:
            daemon.start()
        elif 'stop' == sys.argv[1]:
            daemon.stop()
        elif 'restart' == sys.argv[1]:
            daemon.restart()
        elif 'version' == sys.argv[1]:
            print "%s - version %s" % (name, cbfidelisbridge.version.__version__)
        else:
            print "Unknown command: %s" % sys.argv[1]
            sys.exit(2)

    else:
        print "Usage: %s start|stop|restart|version" % sys.argv[0]
        sys.exit(2)

